### PR TITLE
Improve Ruby and Rails compatibility

### PR DESCRIPTION
**Pull request by a2ikm**
This PR improves compatibilities and tests with CRuby 2.2+ and Rails 4.2+.

### CODE REVIEW

**Comment by jingweno** [comment]
Thanks!

**Comment by a2ikm** [comment]
Thank you!

**Comment by pedro** [comment]
Nice! @jingweno can you cut a new release with these in? 😬👌

**Comment by jingweno** [comment]
You got it @pedro: https://rubygems.org/gems/msgpack_rails/versions/0.4.3. And 👋 😄

**Comment by pedro** [comment]
wow, rocking - thank you! hai indeed :}

**Pull request merged**
