### PR TITLE
Implement parsing msgpack parameter

### PR DESCRIPTION
**Pull request by a2ikm**
This PR implements parsing msgpack request body with `Content-Type: application/msgpack` header.

### CODE REVIEW

**Comment by jingweno** [comment]
LGTM. Thanks!

**Comment by a2ikm** [comment]
Thank you!

**Comment by hiradyazdan** [comment]
@jingweno Is this on latest version v0.4.3? pulling from ruby gems can't see this there.

**Comment by hiradyazdan** [comment]
@a2ikm Also, it would be nice if there was also a raw array format parser by which attributes could be matched with the index of the array (in specific order) rather than a hash key/value pair and parsed to activerecord attributes. I'm thinking the challenge would be how to give active record attributes a specific index key through which they match with the decoded msgpack array.

**Pull request merged**
